version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports: [ "27017:27017" ]
    environment:
      MONGO_INITDB_DATABASE: inventorydb
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      MONGODB_URI: mongodb://mongo:27017/inventorydb
      JWT_SECRET: super-secret-change-me
      CORS_ALLOWED_ORIGINS: http://localhost:5173
    ports: [ "8080:8080" ]
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8080
    ports: [ "5173:80" ]
    depends_on:
      - backend

volumes:
  mongo_data:
